In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba_games.csv", index_col=0)
#sort by date
df = df.sort_values("date")
#resetting the column number
df = df.reset_index(drop=True)

In [5]:
#deleting redundant columns
del df["mp.1"]
del df ["mp_opp.1"]
del df["index_opp"]

In [6]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20407,240.0,34.0,92.0,0.370,11.0,35.0,0.314,15.0,19.0,0.789,...,21.5,33.4,202.0,113.0,DEN,109,0,2023,2023-06-07,False
20408,240.0,39.0,79.0,0.494,14.0,28.0,0.500,16.0,21.0,0.762,...,25.2,30.3,223.0,127.0,MIA,95,1,2023,2023-06-09,True
20409,240.0,35.0,78.0,0.449,8.0,25.0,0.320,17.0,20.0,0.850,...,50.0,32.6,164.0,114.0,DEN,108,0,2023,2023-06-09,False
20410,240.0,33.0,96.0,0.344,9.0,35.0,0.257,14.0,16.0,0.875,...,28.6,26.4,202.0,104.0,DEN,94,1,2023,2023-06-12,False
20411,240.0,38.0,84.0,0.452,5.0,28.0,0.179,13.0,23.0,0.565,...,25.0,42.5,102.0,109.0,MIA,89,0,2023,2023-06-12,True

In [ ]:
df = df.copy()

In [7]:
#creates an additional row to show train the model if won the next game or not
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\4250365674.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)

In [ ]:
df = df.copy()

In [8]:
#make those that have not been out yet yield 2
df["target"][pd.isnull(df["target"])] = 2

C:\Users\cools\AppData\Local\Temp\ipykernel_3488\493764713.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [10]:
# change true and false to 1 and 0 and leave rest
df["target"] = df["target"].astype(int, errors="ignore")

In [11]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20407,240.0,34.0,92.0,0.370,11.0,35.0,0.314,15.0,19.0,0.789,...,33.4,202.0,113.0,DEN,109,0,2023,2023-06-07,False,0
20408,240.0,39.0,79.0,0.494,14.0,28.0,0.500,16.0,21.0,0.762,...,30.3,223.0,127.0,MIA,95,1,2023,2023-06-09,True,1
20409,240.0,35.0,78.0,0.449,8.0,25.0,0.320,17.0,20.0,0.850,...,32.6,164.0,114.0,DEN,108,0,2023,2023-06-09,False,0
20410,240.0,33.0,96.0,0.344,9.0,35.0,0.257,14.0,16.0,0.875,...,26.4,202.0,104.0,DEN,94,1,2023,2023-06-12,False,2
20411,240.0,38.0,84.0,0.452,5.0,28.0,0.179,13.0,23.0,0.565,...,42.5,102.0,109.0,MIA,89,0,2023,2023-06-12,True,2

In [12]:
#checking how many columns are null to remove
nulls = pd.isnull(df)

In [13]:
#sum up the null = true columns
nulls = nulls.sum()

In [14]:
nulls

mp          0
fg          0
fga         0
fg%         0
3p          0
           ..
home_opp    0
season      0
date        0
won         0
target      0
Length: 148, dtype: int64

In [15]:
nulls = nulls[nulls > 0] #only having the null columns

In [16]:
nulls

+/-             20412
mp_max          20412
mp_max.1        20412
+/-_max            15
+/-_opp         20412
mp_max_opp      20412
mp_max_opp.1    20412
+/-_max_opp        15
dtype: int64

In [17]:
#checking the df column if it is not in the nulls index
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [18]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=140)

In [19]:
df = df[valid_columns].copy()

In [20]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20407,240.0,34.0,92.0,0.370,11.0,35.0,0.314,15.0,19.0,0.789,...,33.4,202.0,113.0,DEN,109,0,2023,2023-06-07,False,0
20408,240.0,39.0,79.0,0.494,14.0,28.0,0.500,16.0,21.0,0.762,...,30.3,223.0,127.0,MIA,95,1,2023,2023-06-09,True,1
20409,240.0,35.0,78.0,0.449,8.0,25.0,0.320,17.0,20.0,0.850,...,32.6,164.0,114.0,DEN,108,0,2023,2023-06-09,False,0
20410,240.0,33.0,96.0,0.344,9.0,35.0,0.257,14.0,16.0,0.875,...,26.4,202.0,104.0,DEN,94,1,2023,2023-06-12,False,2
20411,240.0,38.0,84.0,0.452,5.0,28.0,0.179,13.0,23.0,0.565,...,42.5,102.0,109.0,MIA,89,0,2023,2023-06-12,True,2

In [22]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [23]:
#scaling values between 0 and 1
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [24]:
#split up by seasons and using only previous seasons to predict future seasons
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]

        train = data[data["season"] < season]
        test = data[data["season"] == season]

        model.fit(train[predictors], train["target"])
        preds = model.predict(test[predictors])
        #convert to pandas
        preds = pd.Series(preds, index=test.index)

        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [25]:
#adding effect of home games benchmark accuracy 
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.427102
1.0    0.572898
dtype: float64

In [26]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.391304,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.151282,0.800948,0.517647,ATL,0.267857,1.0,2016,2015-10-27,True,1
1,0.0,0.391304,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.020513,0.203791,0.317647,DET,0.375000,0.0,2016,2015-10-27,False,1
2,0.0,0.413043,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.161538,0.345972,0.317647,CHI,0.294643,1.0,2016,2015-10-27,False,1
3,0.0,0.391304,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.089744,0.232227,0.329412,CLE,0.276786,0.0,2016,2015-10-27,True,1
4,0.0,0.347826,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.278205,0.554502,0.317647,GSW,0.419643,1.0,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20407,0.0,0.326087,0.470588,0.241627,0.379310,0.469697,0.372922,0.325581,0.285714,0.753792,...,0.146154,0.535545,0.423529,DEN,0.401786,0.0,2023,2023-06-07,False,0
20408,0.0,0.434783,0.279412,0.538278,0.482759,0.363636,0.593824,0.348837,0.317460,0.722287,...,0.106410,0.635071,0.588235,MIA,0.276786,1.0,2023,2023-06-09,True,1
20409,0.0,0.347826,0.264706,0.430622,0.275862,0.318182,0.380048,0.372093,0.301587,0.824971,...,0.135897,0.355450,0.435294,DEN,0.392857,0.0,2023,2023-06-09,False,0
20410,0.0,0.304348,0.529412,0.179426,0.310345,0.469697,0.305226,0.302326,0.238095,0.854142,...,0.056410,0.535545,0.317647,DEN,0.267857,1.0,2023,2023-06-12,False,2
20411,0.0,0.413043,0.352941,0.437799,0.172414,0.363636,0.212589,0.279070,0.349206,0.492415,...,0.262821,0.061611,0.376471,MIA,0.223214,0.0,2023,2023-06-12,True,2

In [27]:
# taking in consideration of the last rolling games
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [28]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.391304,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.071,0.550314,0.151282,0.800948,0.517647,0.267857,1.0,True,DET,2016
1,0.0,0.391304,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.047,0.300839,0.020513,0.203791,0.317647,0.375000,0.0,False,ATL,2016
2,0.0,0.413043,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.140,0.509434,0.161538,0.345972,0.317647,0.294643,1.0,False,CLE,2016
3,0.0,0.391304,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.185,0.270440,0.089744,0.232227,0.329412,0.276786,0.0,True,CHI,2016
4,0.0,0.347826,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.079,0.679245,0.278205,0.554502,0.317647,0.419643,1.0,False,NOP,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20407,0.0,0.326087,0.470588,0.241627,0.379310,0.469697,0.372922,0.325581,0.285714,0.753792,...,0.088,0.177149,0.146154,0.535545,0.423529,0.401786,0.0,False,MIA,2023
20408,0.0,0.434783,0.279412,0.538278,0.482759,0.363636,0.593824,0.348837,0.317460,0.722287,...,0.216,0.215933,0.106410,0.635071,0.588235,0.276786,1.0,True,DEN,2023
20409,0.0,0.347826,0.264706,0.430622,0.275862,0.318182,0.380048,0.372093,0.301587,0.824971,...,0.073,0.475891,0.135897,0.355450,0.435294,0.392857,0.0,False,MIA,2023
20410,0.0,0.304348,0.529412,0.179426,0.310345,0.469697,0.305226,0.302326,0.238095,0.854142,...,0.261,0.251572,0.056410,0.535545,0.317647,0.267857,1.0,False,MIA,2023
20411,0.0,0.413043,0.352941,0.437799,0.172414,0.363636,0.212589,0.279070,0.349206,0.492415,...,0.121,0.213836,0.262821,0.061611,0.376471,0.223214,0.0,True,DEN,2023

In [29]:
def find_team_averages(team):
    rolling = team.rolling(10).mean(numeric_only=True)
    return rolling

In [30]:
#using rolling average on team and season
df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

In [31]:
#renaming columns to avoid overlap when merging df and df_rolling
rolling_cols = {f"{col}_10" for col in df_rolling.columns}
df_rolling.columns = rolling_cols

#adding columns to make a wide dataframe
df = pd.concat([df, df_rolling], axis=1)

In [32]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,pts_10,ast%_max_opp_10,stl_10,drtg_max_opp_10,ftr_10,efg%_max_opp_10,usg%_max_opp_10,3pa_max_10,3p%_10,total_10
0,0.0,0.391304,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.391304,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.413043,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.391304,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.347826,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20407,0.0,0.326087,0.470588,0.241627,0.379310,0.469697,0.372922,0.325581,0.285714,0.753792,...,0.398739,0.0454,0.0872,0.233124,0.245256,0.500000,0.560000,0.373214,0.6,2023.0
20408,0.0,0.434783,0.279412,0.538278,0.482759,0.363636,0.593824,0.348837,0.317460,0.722287,...,0.321330,0.0458,0.0883,0.319811,0.340769,0.425118,0.628235,0.359821,0.5,2023.0
20409,0.0,0.347826,0.264706,0.430622,0.275862,0.318182,0.380048,0.372093,0.301587,0.824971,...,0.397706,0.0452,0.0910,0.262998,0.246154,0.490521,0.535294,0.366071,0.5,2023.0
20410,0.0,0.304348,0.529412,0.179426,0.310345,0.469697,0.305226,0.302326,0.238095,0.854142,...,0.422821,0.0465,0.1108,0.257547,0.237949,0.512322,0.512941,0.356250,0.5,2023.0
20411,0.0,0.413043,0.352941,0.437799,0.172414,0.363636,0.212589,0.279070,0.349206,0.492415,...,0.322592,0.0379,0.0812,0.316038,0.350641,0.375355,0.603529,0.348214,0.5,2023.0

In [33]:
df = df.dropna()

In [34]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,pts_10,ast%_max_opp_10,stl_10,drtg_max_opp_10,ftr_10,efg%_max_opp_10,usg%_max_opp_10,3pa_max_10,3p%_10,total_10
243,0.0,0.500000,0.382353,0.523923,0.344828,0.333333,0.457245,0.255814,0.238095,0.708285,...,0.311927,0.0628,0.0679,0.413522,0.125256,0.361611,0.449412,0.322321,0.4,2016.0
249,0.0,0.630435,0.426471,0.645933,0.620690,0.515152,0.562945,0.325581,0.238095,0.927655,...,0.412271,0.0613,0.0772,0.469497,0.220641,0.394787,0.531765,0.300893,0.5,2016.0
252,0.0,0.326087,0.250000,0.413876,0.310345,0.257576,0.509501,0.511628,0.412698,0.827305,...,0.458257,0.0699,0.1072,0.380294,0.274359,0.270616,0.478824,0.286607,0.6,2016.0
254,0.0,0.456522,0.500000,0.375598,0.379310,0.348485,0.483373,0.441860,0.396825,0.730455,...,0.331537,0.0657,0.1032,0.437212,0.126026,0.404739,0.408235,0.398214,0.2,2016.0
256,0.0,0.282609,0.235294,0.363636,0.344828,0.348485,0.439430,0.627907,0.476190,0.886814,...,0.398280,0.0747,0.0742,0.303564,0.131667,0.387678,0.410588,0.325893,0.5,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20407,0.0,0.326087,0.470588,0.241627,0.379310,0.469697,0.372922,0.325581,0.285714,0.753792,...,0.398739,0.0454,0.0872,0.233124,0.245256,0.500000,0.560000,0.373214,0.6,2023.0
20408,0.0,0.434783,0.279412,0.538278,0.482759,0.363636,0.593824,0.348837,0.317460,0.722287,...,0.321330,0.0458,0.0883,0.319811,0.340769,0.425118,0.628235,0.359821,0.5,2023.0
20409,0.0,0.347826,0.264706,0.430622,0.275862,0.318182,0.380048,0.372093,0.301587,0.824971,...,0.397706,0.0452,0.0910,0.262998,0.246154,0.490521,0.535294,0.366071,0.5,2023.0
20410,0.0,0.304348,0.529412,0.179426,0.310345,0.469697,0.305226,0.302326,0.238095,0.854142,...,0.422821,0.0465,0.1108,0.257547,0.237949,0.512322,0.512941,0.356250,0.5,2023.0
20411,0.0,0.413043,0.352941,0.437799,0.172414,0.363636,0.212589,0.279070,0.349206,0.492415,...,0.322592,0.0379,0.0812,0.316038,0.350641,0.375355,0.603529,0.348214,0.5,2023.0

In [35]:
#giving information of the next game, home

#group by team and grab
def shift_col(team, col_name):
    #taking value of next game and shift a column by 1
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    #next game home value of the team
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
#information of next game
df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

C:\Users\cools\AppData\Local\Temp\ipykernel_3488\1575830935.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\1575830935.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
C:\Users\cools\AppData\Local\Temp\ipykernel_3488\1575830935.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [36]:
print("team_opp_next" in df)

True

In [37]:
df = df.copy()

In [38]:
#pulling data of opposite team cols to give information on how the next opponent is doing
full = df.merge(
    df[list(rolling_cols) + ["team_opp_next", "date_next", "team"]],
    left_on=["team", "date_next"],
    right_on=["team_opp_next", "date_next"]
)

In [39]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl_10_y,drtg_max_opp_10_y,ftr_10_y,efg%_max_opp_10_y,usg%_max_opp_10_y,3pa_max_10_y,3p%_10_y,total_10_y,team_opp_next_y,team_y
0,0.0,0.326087,0.250000,0.413876,0.310345,0.257576,0.509501,0.511628,0.412698,0.827305,...,0.1032,0.437212,0.126026,0.404739,0.408235,0.398214,0.2,2016.0,TOR,SAC
1,0.0,0.456522,0.500000,0.375598,0.379310,0.348485,0.483373,0.441860,0.396825,0.730455,...,0.1072,0.380294,0.274359,0.270616,0.478824,0.286607,0.6,2016.0,SAC,TOR
2,0.0,0.326087,0.558824,0.186603,0.206897,0.469697,0.203088,0.139535,0.111111,0.854142,...,0.0766,0.413732,0.157821,0.470142,0.391765,0.405357,0.6,2016.0,DEN,NOP
3,0.0,0.413043,0.397059,0.401914,0.137931,0.212121,0.263658,0.418605,0.365079,0.757293,...,0.0726,0.468868,0.124231,0.332227,0.407059,0.343750,0.5,2016.0,ORL,MIN
4,0.0,0.304348,0.323529,0.318182,0.275862,0.272727,0.432304,0.186047,0.158730,0.787631,...,0.0839,0.310377,0.128205,0.312796,0.410588,0.328571,0.5,2016.0,PHI,DAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18129,0.0,0.434783,0.220588,0.600478,0.379310,0.363636,0.466746,0.418605,0.333333,0.841307,...,0.1092,0.228616,0.243077,0.473460,0.562353,0.358036,0.6,2023.0,DEN,MIA
18130,0.0,0.478261,0.294118,0.583732,0.172414,0.212121,0.330166,0.488372,0.412698,0.784131,...,0.0872,0.233124,0.245256,0.500000,0.560000,0.373214,0.6,2023.0,DEN,MIA
18131,0.0,0.326087,0.470588,0.241627,0.379310,0.469697,0.372922,0.325581,0.285714,0.753792,...,0.0710,0.314361,0.340897,0.411848,0.642353,0.390179,0.5,2023.0,MIA,DEN
18132,0.0,0.434783,0.279412,0.538278,0.482759,0.363636,0.593824,0.348837,0.317460,0.722287,...,0.0910,0.262998,0.246154,0.490521,0.535294,0.366071,0.5,2023.0,DEN,MIA
18133,0.0,0.347826,0.264706,0.430622,0.275862,0.318182,0.380048,0.372093,0.301587,0.824971,...,0.0883,0.319811,0.340769,0.425118,0.628235,0.359821,0.5,2023.0,MIA,DEN

In [40]:
#select columns that wont fit in model
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [41]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [77]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
rr = RidgeClassifier(alpha=1)
xgbmodel = xgb.XGBClassifier()
rf = RandomForestClassifier()
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="backward", cv=split)

In [95]:
#sfs.fit(full[selected_columns], full["target"])

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [105]:
import numpy as np
xgbmodel.fit(full[selected_columns], full["target"])
indices = np.argsort(xgbmodel.feature_importances_)[::-1]
print(indices)
# Select the top N features (e.g., top 30)
top_n = 800
selected_feature_indices = indices[:top_n]

# Get the names of the selected features
predictors = full[selected_columns].columns[selected_feature_indices]
print(predictors)
# Print or use the selected feature names

[269 301 165 302 166 289 216 320 184 265 153 352 362 401 116 224 159 357
 355 152 288 290 392 115 338 154 303 108 295 202 334 274 192 223 268 147
  33 315 309 226  62 275 197 360 365 332  73 316  83 346 323 228 138 198
 283 314 270  51 167 311 137 150 173 373 318 191 170 339 387  68  77 291
 134 393 378 374 185  45  27  90 282 171 306 187 189 394 146  70 297 230
 281 218 333 327 193 276 213  92 196 271 100 148 160  57 151 236 204 174
 124 122 342 181 264 386 210 131 299 155 188  37 350  19 294 222 286   7
 117 396 343  56  86 376 310 366 229  24  96 260 142  55 215 227 308 156
 347 287 385 345 123 340 279 284 363 250  26  69 395  63 221 161  32 179
 331  58  28 158 364 211  20 130  49 375 256 317 278 207 351 397   3 253
 103   6 244 203   5 208 258 149 328 195 254 336 372 118  89 280   1  29
 296 101 127  23 325 390 239 255 178 251 313 329 143  74 205 121  12 235
  59 356 113 359 354 200  22 304 163 324 319 262 380 341 219 112  88  44
 252 105 361 172 162  47  35   8  94 322 382 273 246 190  87  85  34 212
 391 114 169 399 182 326 371 120 238 194 110 177  25 257 358 183 353 383
 102 214 129 261 109 225 348  18 277  21 330  60 349  14 140 263  78  50
 139  64 389  11 388 237 377 400 398  84 307  95 249  93 126  38  79  40
 305   2 145  31  76  53 206 125 312 379 135  71 104  72 157 321 243  52
 247 106 245 292  66 128 381 186 240 285   4  75 234 217 248  61   9 136
 119 220 298 209  80 180 175 344  54  39 370 259 176 168 293  41 144 242
  15 107  42  46 272  17 111 241  48  43  16  91  13  82 384 141  36  81
  10 404  30 232 402 369 368 367 337 335 300 267 266 233 231  65 403 201
 199 164 133 132  99  98  97  67   0]
Index(['home_next', 'trb_max_10_y', 'trb_max_10_x', 'drb_max_opp_10_y',
       'drb_max_opp_10_x', '3p%_max_10_y', '3pa_10_x', 'orb%_max_opp_10_y',
       'orb%_max_opp_10_x', 'usg%_max_opp_10_x',
       ...
       '3par_opp_10_x', 'fga_10_x', 'trb%_opp_10_x', 'home_opp', 'total_opp',
       'drtg_opp', 'ortg_opp', 'usg%_opp', 'mp_opp', 'mp'],
      dtype='object', length=405)

In [102]:
#predictors = list(selected_columns[sfsforest.get_support()])

In [103]:
predictions = backtest(full, xgbmodel, predictors)

In [104]:
from sklearn.metrics import accuracy_score

accuracy_score(predictions["actual"], predictions["prediction"])

0.5988704763320205